version: 2.1
orbs:
  node: circleci/node@4.2.0
jobs:
  build:
    executor:
        name: node/node
        tag: latest
    working_directory: ~/repo
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - node/with-cache:
          dir: ~/repo/node_modules
          cache-version: v1
          steps:
          - run: npm install
          - run:
              name: build
              command: npm run build
workflows:
  version: 2
  build:
    jobs:
      - build