version: '2.1'
orbs:
  node: circleci/node@4.2.0
jobs:
  test:
    executor:
      name: node/default
      tag: '12.16.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run YARN tests
          command: yarn run test
workflows:
  test_my_app:
    jobs:
      - test